version: '3'
networks:
  outline-importer-confluence_network_compose:
    driver: bridge 
services:
  outline-importer-confluence:
    container_name: outline-importer-confluence
    build: .
    restart: unless-stopped
    networks:
      outline-importer-confluence_network_compose:
    ports:
    - "8081:8081"
